app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: TianQue
publisher_url: https://www.tianque.cc
display_name: TianQue
executable_name: TianQue.exe
output_base_file_name: TianQue.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\TianQue"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
